<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net481</TargetFramework>
		<LangVersion>Preview</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<Company>M4rbleL1ne</Company>
	</PropertyGroup>
	<ItemGroup>
		<Reference Include="Assembly-CSharp">
			<HintPath>Refs\PUBLIC-Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="BepInEx">
			<HintPath>Refs\BepInEx.dll</HintPath>
		</Reference>
		<Reference Include="HOOKS-Assembly-CSharp">
			<HintPath>Refs\HOOKS-Assembly-CSharp.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Mathematics">
			<HintPath>Refs\Unity.Mathematics.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine">
			<HintPath>Refs\UnityEngine.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>Refs\UnityEngine.CoreModule.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>