<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ClearWaterPlugin</AssemblyName>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>Preview</LangVersion>
    <Company>Garrakx and M4rbleL1ne</Company>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>Refs\PUBLIC-Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx">
      <HintPath>Refs\BepInEx.dll</HintPath>
    </Reference>
    <Reference Include="HOOKS-Assembly-CSharp">
      <HintPath>Refs\HOOKS-Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>Refs\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>Refs\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>